# Generated by Django 5.2 on 2025-07-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('week_number', models.IntegerField()),
                ('category', models.CharField(choices=[('Word', 'Word'), ('Outlook', 'Outlook'), ('Shortcut', 'Shortcut'), ('Other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_number', '-created_at'],
            },
        ),
    ]
