# Generated by Django 5.2 on 2025-07-06 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='employee_update_notes',
            field=models.TextField(blank=True, help_text='Notes about changes made by employee'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_employee_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
